# ชื่อของ Workflow
name: MLOps Pipeline CI/CT/CD

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  # --- JOB ใหม่ที่เพิ่มเข้ามาสำหรับ CI ---
  ci-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mlops_pipeline/requirements.txt
        pip install flake8 pytest pandas

    - name: Lint with flake8
      run: |
        flake8 mlops_pipeline/scripts --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 mlops_pipeline/scripts --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest || (if [ $? -eq 5 ]; then echo "Pytest finished: No tests found."; exit 0; else exit $?; fi)


  build-and-train:
    needs: ci-checks
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mlops_pipeline/requirements.txt
        # ติดตั้ง NLTK + ดาวน์โหลด vader_lexicon
        pip install nltk
        python -m nltk.downloader vader_lexicon --quiet

    - name: Set MLflow tracking path (Linux safe)
      run: |
        export MLFLOW_TRACKING_URI=file:./mlruns_temp

    - name: Run Data Validation
      run: python mlops_pipeline/scripts/01_data_validation.py

    - name: Run Data Preprocessing
      id: preprocessing
      run: |
        RUN_ID=$(python mlops_pipeline/scripts/02_data_preprocessing.py | grep "run_id=" | cut -d'=' -f2)
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

    - name: Run Model Training, Evaluation, and Registration
      run: python mlops_pipeline/scripts/03_train_evaluate_register.py ${{ steps.preprocessing.outputs.run_id }} 0.5 word "(1,4)" 800000 1.2

    - name: Transition Model to Staging
      if: success()
      run: python mlops_pipeline/scripts/04_transition_model.py "mental-health-classifier" "Staging"

    - name: Upload MLflow artifacts for inspection
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: mlruns/
