# ชื่อของ Workflow
name: MLOps Pipeline CI/CT/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- JOB สำหรับ CI ---
  ci-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mlops_pipeline/requirements.txt
        pip install flake8 pytest pandas

    - name: Lint with flake8
      run: |
        flake8 mlops_pipeline/scripts --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 mlops_pipeline/scripts --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest || (if [ $? -eq 5 ]; then echo "Pytest finished: No tests found."; exit 0; else exit $?; fi)

  # --- JOB สำหรับ Train + Register ---
  build-and-train:
    needs: ci-checks
    runs-on: ubuntu-latest

    env:
      # ใช้ local tracking URI แทน secrets สำหรับ workflow นี้
      MLFLOW_TRACKING_URI: file:./mlruns_temp

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mlops_pipeline/requirements.txt
        pip install nltk
        python -m nltk.downloader vader_lexicon --quiet

    # ตรวจสอบและสร้างโฟลเดอร์ mlruns_temp
    - name: Prepare MLflow directory
      run: mkdir -p mlruns_temp && echo "Created local MLflow dir: mlruns_temp"

    # Data Validation
    - name: Run Data Validation
      run: python mlops_pipeline/scripts/01_data_validation.py

    # Data Preprocessing
    - name: Run Data Preprocessing
      id: preprocessing
      run: |
        RUN_ID=$(python mlops_pipeline/scripts/02_data_preprocessing.py | grep "run_id=" | cut -d'=' -f2)
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

    # Model Training + Evaluation + Register
    - name: Run Model Training, Evaluation, and Registration
      run: |
        echo "Using run_id: ${{ steps.preprocessing.outputs.run_id }}"
        python mlops_pipeline/scripts/03_train_evaluate_register.py ${{ steps.preprocessing.outputs.run_id }} 0.4 word "(1,4)" 444444 1.4

    # Transition Model
    - name: Transition Model to Staging
      if: success()
      run: python mlops_pipeline/scripts/04_transition_model.py "mental-health-classifier" "Staging"

    # Upload artifacts
    - name: Upload MLflow artifacts for inspection
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: mlruns_temp/
